function [idDaPessoa] = escolherPessoaDaFoto()
%UNTITLED12 Summary of this function goes here
%   Detailed explanation goes here

    addpath ../Functions
    
    idDaPessoa = 0;
   
    load BancoDeDados cadastro

    telaEscolhaDaPessoa = figure('Name', 'TCC Eng. Controle e Automação'); 

        label = uicontrol('Style', 'text',...
                'String', 'PREENCHER CADASTRO -> ESCOLHER PESSOA POR NÚMERO',...
                'Position', [85 360 400 30]...
                );
    
        botao1 = uicontrol('Style', 'pushbutton',...
                'String', '1',...
                'Position', [40 300 50 50],...
                'Callback', @(src, evnt)acaoBotao(1),...
                'Enable', checarSeDeveHabilitarBotao(1)...
                );
            
        edit1 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(1),...
            'Position', [100 300 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(1),...
            'Enable', checarSeDeveHabilitarEdit(1)...
            );

        botao2 = uicontrol('Style', 'pushbutton',...
                'String', '2',...
                'Position', [40 230 50 50],...
                'Callback', @(src, evnt)acaoBotao(2),...
                'Enable', checarSeDeveHabilitarBotao(2)...
                );
            
        edit2 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(2),...
            'Position', [100 230 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(2),...
            'Enable', checarSeDeveHabilitarEdit(2)...
            );

        botao3 = uicontrol('Style', 'pushbutton',...
                'String', '3',...
                'Position', [40 160 50 50],...
                'Callback', @(src, evnt)acaoBotao(3),...
                'Enable', checarSeDeveHabilitarBotao(3)...
                );
            
        edit3 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(3),...
            'Position', [100 160 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(3),...
            'Enable', checarSeDeveHabilitarEdit(3)...
            );        
            
        botao4 = uicontrol('Style', 'pushbutton',...
                'String', '4',...
                'Position', [40 90 50 50],...
                'Callback', @(src, evnt)acaoBotao(4),...
                'Enable', checarSeDeveHabilitarBotao(4)...
                );
            
        edit4 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(4),...
            'Position', [100 90 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(4),...
            'Enable', checarSeDeveHabilitarEdit(4)...
            );
        
        botao5 = uicontrol('Style', 'pushbutton',...
                'String', '5',...
                'Position', [280 300 50 50],...
                'Callback', @(src, evnt)acaoBotao(5),...
                'Enable', checarSeDeveHabilitarBotao(5)...
                );
            
        edit5 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(5),...
            'Position', [340 300 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(5),...
            'Enable', checarSeDeveHabilitarEdit(5)...
            );

        botao6 = uicontrol('Style', 'pushbutton',...
                'String', '6',...
                'Position', [280 230 50 50],...
                'Callback', @(src, evnt)acaoBotao(6),...
                'Enable', checarSeDeveHabilitarBotao(6)...
                );
            
        edit6 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(6),...
            'Position', [340 230 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(6),...
            'Enable', checarSeDeveHabilitarEdit(6)...
            );

        botao7 = uicontrol('Style', 'pushbutton',...
                'String', '7',...
                'Position', [280 160 50 50],...
                'Callback', @(src, evnt)acaoBotao7(),...
                'Enable', checarSeDeveHabilitarBotao(7)...
                );
            
        edit7 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(7),...
            'Position', [340 160 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(7),...
            'Enable', checarSeDeveHabilitarEdit(7)...
            );        
            
        botao8 = uicontrol('Style', 'pushbutton',...
                'String', '8',...
                'Position', [280 90 50 50],...
                'Callback', @(src, evnt)acaoBotao(8),...
                'Enable', checarSeDeveHabilitarBotao(8)...
                );
            
        edit8 = uicontrol('Parent', telaEscolhaDaPessoa,...
            'Style', 'edit',...
            'String', cadastro.nomeDoID(8),...
            'Position', [340 90 150 50],...
            'KeyReleaseFcn', @(src, evnt)acaoEdit(8),...
            'Enable', checarSeDeveHabilitarEdit(8)...
            );

    uiwait(telaEscolhaDaPessoa);
        
    function acaoBotao(numeroDoBotao)
        
        %if length(nomeEscritoNaEdit(numeroDoBotao)) > 0
        idDaPessoa = numeroDoBotao;
        guardarNomesNoCadastro(numeroDoBotao);
        uiresume(telaEscolhaDaPessoa);
        delete(telaEscolhaDaPessoa);
        %else
        %    mudarEstadoDoBotao(numeroDoBotao, 'off');
        %end
    end

    function acaoEdit(numeroDaEdit)
        
        mudarEstadoDoBotao(numeroDaEdit, 'on');
    end

    function habilitar = checarSeDeveHabilitarBotao(numeroDoBotao)
        
        if numeroDoBotao <= cadastro.tamanhoDoVetorDosNomes
            habilitar = 'on';
        else
            habilitar = 'off';
        end
    end

    function habilitar = checarSeDeveHabilitarEdit(numeroDaEdit)
        
        if numeroDaEdit == cadastro.tamanhoDoVetorDosNomes + 1
            habilitar = 'on';
        else
            habilitar = 'off';
        end
    end

    function guardarNomesNoCadastro(botaoApertado)

        if botaoApertado > cadastro.tamanhoDoVetorDosNomes
           
            cadastro.adicionarNome(nomeEscritoNaEdit(botaoApertado));
        end
        
        save BancoDeDados cadastro
    end

    function nome = nomeEscritoNaEdit(numeroDaEdit)
        
        switch numeroDaEdit
            
            case 1
                nome = get(edit1,'String');
            case 2
                nome = get(edit2,'String');
            case 3
                nome = get(edit3,'String');
            case 4
                nome = get(edit4,'String');
            case 5
                nome = get(edit5,'String');
            case 6
                nome = get(edit6,'String');
            case 7
                nome = get(edit7,'String');
            case 8
                nome = get(edit8,'String');
        end
    end

    function mudarEstadoDoBotao(numeroDoBotao, estado)
        
        switch numeroDoBotao
           
            case 1
                set(botao1,'Enable', estado);
            case 2
                set(botao2,'Enable', estado);
            case 3
                set(botao3,'Enable', estado);
            case 4
                set(botao4,'Enable', estado);
            case 5
                set(botao5,'Enable', estado);
            case 6
                set(botao6,'Enable', estado);
            case 7
                set(botao7,'Enable', estado);
            case 8
                set(botao8,'Enable', estado);
        end
    end

end

