subplot(3,1,1)
gerarGraficoAPartirDoArquivo('./Results/Luis Viola PID/LuminanciaS.txt', 'b', 37)
title('Luminância S')
axis([0 150 15 60])
subplot(3,1,2)
gerarGraficoAPartirDoArquivo('./Results/Luis Viola PID/LuminanciaNE.txt', 'b', 42)
title('Luminância NE')
axis([0 150 15 60])
subplot(3,1,3)
gerarGraficoAPartirDoArquivo('./Results/Luis Viola PID/LuminanciaNW.txt', 'b', 42)
title('Luminância NW')
axis([0 150 15 60])